### ISSUE TITLE
define-primop

### ISSUE THREAD

**Issue by stchang** [naoyafurudono/play-with-turnstile#1]
FYI, [`define-primop`](https://docs.racket-lang.org/turnstile/The_Turnstile_Reference.html?#%28form._%28%28lib._turnstile%2Fmain..rkt%29._define-primop%29%29) is a more concise way to add types to primitive functions.

There's also [`typed-out`](https://docs.racket-lang.org/turnstile/The_Turnstile_Reference.html?#%28form._%28%28lib._turnstile%2Fmain..rkt%29._typed-out%29%29) which is the `provide` transformer equivalent.

[Here is an example of some uses](https://github.com/stchang/macrotypes/blob/master/turnstile-example/turnstile/examples/ext-stlc.rkt)

**Comment by naoyafurudono** [comment]
I understand it. Thank you to telling me. And I was very happy to talk to you yesterday.
